# Generated by Django 5.1 on 2024-08-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_users_alter_note_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='confirm_password',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
