# Generated by Django 5.1 on 2024-08-22 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_users_password_remove_users_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='phone_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
