# Generated by Django 5.1 on 2024-08-22 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_users_password_users_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='confirm_password',
        ),
        migrations.RemoveField(
            model_name='users',
            name='password',
        ),
        migrations.RemoveField(
            model_name='users',
            name='username',
        ),
    ]
