# Generated by Django 5.1 on 2024-08-22 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_users_confirm_password_remove_users_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='user',
        ),
        migrations.AddField(
            model_name='users',
            name='confirm_password',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
